### ISSUE TITLE
Rename `radec` to `lonlat`?

### ISSUE THREAD

**Issue by cdeil** [spacetelescope/sphere#42]
I had a quick look at this package ... thanks for releasing it ... I'll definitely use it from now on!

I have one API suggestion: rename `radec` to `lonlat` in the following functions:
* [radec_to_vector](http://spacetelescope.github.io/sphere/api/spherical_geometry.vector.radec_to_vector.html)
* [vector_to_radec](http://spacetelescope.github.io/sphere/api/spherical_geometry.vector.vector_to_radec.html)
* [SphericalPolygon.from_radec](http://spacetelescope.github.io/sphere/api/spherical_geometry.polygon.SphericalPolygon.html#spherical_geometry.polygon.SphericalPolygon.from_radec)
* [SphericalPolygon.to_radec](http://spacetelescope.github.io/sphere/api/spherical_geometry.polygon.SphericalPolygon.html#spherical_geometry.polygon.SphericalPolygon.to_radec)

Everything else in this package is just spherical geometry, and IMO it would be better if someone that uses it with Galactic or Earth coordinates doesn't have to write `radec` here.

If you agree, do you have existing code that uses these functions and we have to do a deprecation process?

**Comment by astrofrog** [comment]
+1 to using lonlat

**Comment by bernie-simon** [comment]
I've added lonlat calls, but kept the radec calls with no deprecation.
