### ISSUE TITLE
Creating poly using from_cone creates variable radius polygons

### ISSUE THREAD

**Issue by djwhiteastro** [spacetelescope/sphere#52]
When creating a new polygon using the SphericalPolygon.from_cone function, there seems to be some strange dependence on the RA of the central point. Using a list of right ascensions for the same declination, all with a radius of 30 degrees, I get the following series of polygons:
![fromconetest](https://cloud.githubusercontent.com/assets/10980327/6624504/ad95b42c-c8e1-11e4-95d6-b4cf9694d831.png)

This is for ras = [0,30,60,90,120,150,180,210,240,270,300,330]

**Comment by bernie-simon** [comment]
I've verified the error. The area varies quite a bit depending on the central point.

**Comment by bernie-simon** [comment]
Found the problem. When code computes a normal vector, it looks for the vector component with minimum magnitude, but doesn't take into account that the component can have a negative value.  It should check the square of the component's value instead of the value itself. Will work on getting a fix in.

**Comment by mdboom** [comment]
@bernie-simon: Sounds plausible.  Thanks!

**Comment by bernie-simon** [comment]
The error only affects generating a polygon using a cone. Other parts of the code are unaffected.

**Comment by djwhiteastro** [comment]
Thanks for looking into this, it seems to work for most cases, but there can still be some variability. For example, using a range of RAs given before, but for a declination of 30 degrees, I still get some variation, which doesn't seem to make sense. It is almost like it is only correctly working out the cones correctly for multiples of 90 degrees in RA. 
![newconetest](https://cloud.githubusercontent.com/assets/10980327/6692388/53fedce0-ccc4-11e4-814c-32d9adaf5498.png)

Cheers, Darren

**Comment by bernie-simon** [comment]
So it looks like there's more than one bug in the code that's causing the problem. Thanks for providing the new error report. Right now getting sphere to work correctly is at the top of my agenda. But I am about to leave on vacation for the next week and a half. If you don't hear from me it's not that I regard the problem as unimportant, it's that I will be out of town.

**Comment by djwhiteastro** [comment]
No problem! I am now not entirely sure that this part of sphere is actually going to be the best solution to my problem, but other parts that do work fine (as far as I can tell) have been incredibly useful for me. Thanks for taking the time to do this!

Darren

**Comment by bernie-simon** [comment]
I was able to duplicate the error, which is something:

E           AssertionError: 
E           Arrays are not almost equal to 7 decimals
E            ACTUAL: 0.70860384008730648
E            DESIRED: 0.84065977345903775

**Comment by mdboom** [comment]
I wonder if we need to use double-double precision for this, too.  That has been the solution elsewhere.  Unfortunately, that means dropping down to C.

Surprisingly, the resolution of points in vector space is not as good as one would think, and it isn't evenly distributed (you get a lot more points near zero as opposed to 1 and -1).  It's probably the kind of problem that should use fixed point rather than floating point arithmetic, but that would be a major overhaul.

**Comment by bernie-simon** [comment]
There were two additional problems with the code. First, the code computes a perpendicular vector in the process of computing the cone and assumes the vector has unit magnitude in all cases. But it did not. So I added a call to normalize the vector. Second, the normalization code itself was incorrect. It treats the case where the magnitude is already one as a special case, but provided no code to implement that case. I removed the special case. The code is sometimes executed redundantly, but that is better than incorrect. Both changes, as well as new test code which exercises the fixes, are in the master branch of the repository and you will get them if you re-install the library.

**Comment by djwhiteastro** [comment]
Looks fine to me now! Thanks again. Fair warning, I have another bug (similar to the assertion error I had and emailed Michael about). When I have got a bit of plain code that replicates the error, I will open up a new issue. But I have a workaround for now, as it is a rare occurrence.
