### ISSUE TITLE
Clarify units for SphericalPolygon.area

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/sphere#59]
The API docs need to make clearer what the return units are for SphericalPolygon.area

**Comment by mdboom** [comment]
The docs say they are in steradians.  Are you saying you want a definition of steradian?

**Comment by astrofrog** [comment]
@mdboom - no, I should have been more specific - I don't see any mention of steardians here:

http://spacetelescope.github.io/sphere/api/spherical_geometry.polygon.SphericalPolygon.html#spherical_geometry.polygon.SphericalPolygon.area

**Comment by mdboom** [comment]
Ah.  It looks like the docs haven't been updated in some time.  @bernie-simon ?

**Comment by bernie-simon** [comment]
I've regenerated the documentation, the changes are small.
