### ISSUE TITLE
Have option to allow auto-closing of Polygons

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/sphere#62]
It would be nice to not have to repeat the first point of the polygon at the end - it is redundant since SphericalPolygon doesn't allow open polygons anyway.

**Comment by mdboom** [comment]
This is primarily a performance optimization.  I have no objections to making the change -- but it should very carefully *not* copy the data if the polygon is already closed.

**Comment by astrofrog** [comment]
To avoid any issues, you could add an option ``auto_close`` defaulting to ``False`` and then if the polygon isn't closed, you can say "If you want to automatically close this polygon, set auto_close=True"?

**Comment by pllim** [comment]
Has this been fixed by #86? If so, this should be closed.

**Comment by bernie-simon** [comment]
Yes, it was fixed, so I am closing this issue.
