### ISSUE TITLE
SphericalPolygon.to_radec should return two values

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/sphere#63]
At the moment I can't do:

```python
    lon, lat = polygon.to_radec()
```

I have to instead do:

```python
    lon, lat = tuple(polygon.to_radec())[0]
```

**Comment by mdboom** [comment]
to_radec returns an iterator over each subpolygon.  Returning all ra, dec points in one go (or just the first set) wouldn't support having subpolygons.

**Comment by astrofrog** [comment]
Ah, I understand - thanks!
