### ISSUE TITLE
Sphinx build broken

### ISSUE THREAD

**Issue by cdeil** [spacetelescope/sphere#66]
Looks like the `sphere` Sphinx build is currently broken:
https://travis-ci.org/spacetelescope/sphere/jobs/67233478#L872

I think you have to update to the latest `astropy-helpers` to fix that.

**Comment by cdeil** [comment]
I think this issue is fixed by #84 
@bernie-simon - Could you please merge that PR?

**Comment by pllim** [comment]
Fixed by #84
