### ISSUE TITLE
Upgrade local astropy_helpers

### ISSUE THREAD

**Issue by evertrol** [spacetelescope/sphere#70]
I just ran into astropy_helpers issue [#144](https://github.com/astropy/astropy-helpers/issues/114) ((`str` vs `bytes` problem in Python 3), but since spherical_geometry uses a local version which precedes the fix by about a month, it still exists in spherical_geometry.
It's a rare case (using spherical_geometry as a module in an empty git directory), but perhaps the astropy_helpers submodule should be updated? Or the fix from the above issue applied.

**Comment by cdeil** [comment]
This issue will probably be fixed by #84

**Comment by pllim** [comment]
Fixed by #84
