### ISSUE TITLE
SphericalPolygon backwards incompatible between 1.0.4 and 1.0.5?

### ISSUE THREAD

**Issue by evertrol** [spacetelescope/sphere#71]
I noticed the SphericalPolygon class has changed between bug-fix versions 4 and 5, to become a placeholder for a set of disjoint polygons. This results in some backwards incompatible changes. 

For example, the specific case I bumped into is that the `inside` attribute now returns a generator. Previously, for a single polygon, I could use:
```python
center = polygon.inside
```
but now I'm doing
```python
center = list(polygon.inside)[0]
```

Perhaps I miss something above, but otherwise this seems a rather drastic change for such a minor (bug-fix?) version change, especially for a version 1.

**Comment by bernie-simon** [comment]
The original design of the sphere package implemented disjoint polygons as a single polygon connected by zero area bridges. This designed proved unworkable when tested, so it was replaced by a tuple of polygons. This inevitably meant breaking the interface, it would have needed  to change to either a tuple based or iterator based interface and the designer, Mike, decided to use iterators. If there was a fault, it was prematurely declaring it a 1.0 version library when without real world use it should have been a beta. I understand that this is a pain point, as we were forced to search the Space Telescope code base and make the needed updates ourselves. There's no plans to make further changes to the interface, although bugs will be fixed when found.

**Comment by evertrol** [comment]
Thanks, that clears it up. So I should stick to the 1.0.5/current mater interface instead?
(I guess there's also the part confusion that pypi list 1.0.4, although the pypi page appears outdated and not installable/downloadable, but it's also part why I assumed 1.0.4 the default interface.)

**Comment by pllim** [comment]
@bernie-simon , do you have plans to update PyPi or waiting for our switch to conda?

**Comment by bernie-simon** [comment]
Yes, I intended to do it a while ago, but forgot when a more pressing problem came up. I've added it onto my list of things to do.

**Comment by bernie-simon** [comment]
PyPi was updated and I will update it again when I finish with the current set of issues. There will be one more "breaking" change (set the range for longitude to 0-360), but having swallowed the camel of negative polygon area, I see no reason to strain at the gnat of 0-360 or 0-2 pi longitude.
