### ISSUE TITLE
Feature request: Allow specification of angle ranges in to_radec()

### ISSUE THREAD

**Issue by mcara** [spacetelescope/sphere#72]
Currently, `SphericalPolygon.to_radec()` returns `RA` in the range [-180,180] degrees while astropy.wcs pix to sky transformations result in `RA` in range [0,360].

Maybe it would be possible to add a parameter that could tell `to_radec` the desired range for output?

**Comment by bernie-simon** [comment]
I've always thought of right ascension as having a value between 0 and 360 degrees, or 0 and 24 hours. But I'm not an astronomer, are negative right ascensions commonly used? I could supply an optional flag, but would prefer to return the nore useful value, as the transformation is trivial.

**Comment by evertrol** [comment]
I agree that the [0, 360] range is more common, or possibly even prescribed somewhere. 
I'm surprised `to_radec()` doesn't do this; This may have an origin in the [-pi, pi] underlying system?

I would mean possibly breaking things and being backwards incompatible, as it changes the output of `to_radec()`.

NB: the straightforward workaround is probably `ra, dec = poly.to_radec(); ra %= 360`. Sadly this is not a one-liner.

**Comment by bernie-simon** [comment]
The more I think about it, the more 0-360 range seems the right thing to do, so yes, I will modify the code.

**Comment by bernie-simon** [comment]
Closing this issue after merging the change.
